### Numpy Random Seed

In [2]:
import numpy as np
# Pseudo-random numbers
# np.random.seed()

random_array_4 = np.random.randint(10, size = (5, 3))
random_array_4

array([[8, 4, 8],
       [2, 1, 9],
       [4, 9, 4],
       [3, 4, 2],
       [8, 4, 6]])

In [4]:
random_array_4 = np.random.rand(3,3)
random_array_4

array([[0.09996853, 0.02199901, 0.36008612],
       [0.16780815, 0.14065103, 0.82866403],
       [0.62347724, 0.04330176, 0.50029282]])

In [8]:
random_array_4 = np.random.random((4, 3))
random_array_4

array([[0.20340311, 0.89268504, 0.62464057],
       [0.26147443, 0.6306854 , 0.49869968],
       [0.09170127, 0.60143814, 0.5849674 ],
       [0.76430748, 0.61470553, 0.99120932]])

In [9]:
## Pseudo-random numbers
#np.random.seed()

random_array_1 = np.random.randint(10, size = (5, 3))
random_array_1


array([[6, 9, 3],
       [0, 5, 9],
       [3, 4, 1],
       [3, 4, 1],
       [0, 3, 8]])

In [10]:
random_array_1.shape

(5, 3)

In [14]:
## Pseudo-random numbers
np.random.seed(seed = 0)

random_array_1 = np.random.randint(10, size = (5, 3))
random_array_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [18]:
np.random.seed(7)
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [20]:
random_array_3 = np.random.random((5,3))
random_array_3

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [22]:
np.random.seed(7)
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])