### Numpy Random Seed

In [2]:
import numpy as np
# Pseudo-random numbers
# np.random.seed()

random_array_4 = np.random.randint(10, size = (5, 3))
random_array_4

array([[8, 4, 8],
       [2, 1, 9],
       [4, 9, 4],
       [3, 4, 2],
       [8, 4, 6]])

In [4]:
random_array_4 = np.random.rand(3,3)
random_array_4

array([[0.09996853, 0.02199901, 0.36008612],
       [0.16780815, 0.14065103, 0.82866403],
       [0.62347724, 0.04330176, 0.50029282]])

In [8]:
random_array_4 = np.random.random((4, 3))
random_array_4

array([[0.20340311, 0.89268504, 0.62464057],
       [0.26147443, 0.6306854 , 0.49869968],
       [0.09170127, 0.60143814, 0.5849674 ],
       [0.76430748, 0.61470553, 0.99120932]])

In [9]:
## Pseudo-random numbers
#np.random.seed()

random_array_1 = np.random.randint(10, size = (5, 3))
random_array_1


array([[6, 9, 3],
       [0, 5, 9],
       [3, 4, 1],
       [3, 4, 1],
       [0, 3, 8]])

In [10]:
random_array_1.shape

(5, 3)

In [14]:
## Pseudo-random numbers
np.random.seed(seed = 0)

random_array_1 = np.random.randint(10, size = (5, 3))
random_array_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [18]:
np.random.seed(7)
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [20]:
random_array_3 = np.random.random((5,3))
random_array_3

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [22]:
np.random.seed(7)
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

### Viewing Arrays and Matrices

In [3]:
import numpy as np


In [7]:
random_array_5 =  np.random.random((5,3))
random_array_5

array([[0.47870519, 0.9508181 , 0.14173359],
       [0.00952128, 0.1389401 , 0.92718261],
       [0.41068993, 0.5454672 , 0.5737649 ],
       [0.41356677, 0.87688803, 0.3282875 ],
       [0.14381351, 0.2498812 , 0.64547922]])

In [8]:
np.unique(random_array_5)

array([0.00952128, 0.1389401 , 0.14173359, 0.14381351, 0.2498812 ,
       0.3282875 , 0.41068993, 0.41356677, 0.47870519, 0.5454672 ,
       0.5737649 , 0.64547922, 0.87688803, 0.92718261, 0.9508181 ])

In [9]:
np.random.seed(seed = 0)

random_array_1 = np.random.randint(10, size = (5, 3))
random_array_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [10]:
np.unique(random_array_1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [15]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[10 ,11 ,12],[13, 14, 15], [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1[0]

1

In [21]:
a2[0]

array([1, 2, 3])

In [22]:
a2[0][1]

2

In [23]:
a3.shape

(2, 3, 3)

In [24]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a3[0][1]

array([4, 5, 6])

In [26]:
a3[0][1][2]

6

In [30]:
a3[:2, :2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [31]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [35]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]])

In [36]:
a4.shape

(2, 3, 4, 5)

In [37]:
a4.ndim

4

In [39]:
## Get the first 4 numbers of the inner most arrays

a4[:,:,:,:4]

array([[[[8, 8, 2, 3],
         [0, 8, 8, 3],
         [2, 8, 4, 3],
         [4, 3, 6, 9]],

        [[0, 8, 5, 9],
         [9, 6, 5, 3],
         [8, 0, 4, 9],
         [5, 7, 8, 8]],

        [[2, 8, 6, 6],
         [1, 6, 8, 8],
         [2, 3, 6, 3],
         [5, 7, 0, 8]]],


       [[[6, 5, 8, 2],
         [9, 7, 5, 3],
         [5, 3, 3, 7],
         [9, 9, 7, 3]],

        [[3, 9, 7, 7],
         [1, 2, 2, 8],
         [5, 8, 4, 0],
         [5, 5, 0, 8]],

        [[1, 0, 3, 8],
         [4, 4, 0, 9],
         [7, 3, 2, 1],
         [2, 1, 4, 2]]]])

In [44]:
a4[:2, :1, :1, :4]

array([[[[8, 8, 2, 3]]],


       [[[6, 5, 8, 2]]]])